export const CREATE_DATA_SOURCE = 'CREATE_DATA_SOURCE';
export const GET_DATA_SOURCE = 'GET_DATA_SOURCE';
export const UPDATE_DATA_SOURCE = 'UPDATE_DATA_SOURCE';
export const REMOVE_DATA_SOURCE = 'REMOVE_DATA_SOURCE';
export const GET_USER_DATA_SOURCES = 'GET_USER_DATA_SOURCES';
export const SET_TEMPLATE_NAME = 'SET_TEMPLATE_NAME';
export const SET_TEMPLATE_DATA_SOURCE = 'SET_TEMPLATE_DATA_SOURCE';
export const SET_TEMPLATE_CHART_TYPE = 'SET_TEMPLATE_CHART_TYPE';