export const CREATE_DATA_SOURCE = 'CREATE_DATA_SOURCE';
export const CREATE_TEMPLATE = 'CREATE_TEMPLATE';

export const UPDATE_DATA_SOURCE = 'UPDATE_DATA_SOURCE';

export const REMOVE_DATA_SOURCE = 'REMOVE_DATA_SOURCE';
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE';

export const GET_USER_DATA_SOURCES = 'GET_USER_DATA_SOURCES';
export const GET_DATA_SOURCE = 'GET_DATA_SOURCE';
export const GET_TEMPLATE = 'GET_TEMPLATE';

export const SET_TEMPLATE_NAME = 'SET_TEMPLATE_NAME';
export const SET_TEMPLATE_DATA_SOURCE = 'SET_TEMPLATE_DATA_SOURCE';
export const SET_TEMPLATE_CHART_TYPE = 'SET_TEMPLATE_CHART_TYPE';
export const SET_TEMPLATE_KEY_SELECTOR = 'SET_TEMPLATE_KEY_SELECTOR';
export const SET_TEMPLATE_MAP_FUNCTION = 'SET_TEMPLATE_MAP_FUNCTION';
export const SET_TEMPLATE_DATA_SOURCE_FILTER_LEFT_VALUE = 'SET_TEMPLATE_DATA_SOURCE_FILTER_LEFT_VALUE';
export const SET_TEMPLATE_DATA_SOURCE_FILTER_COMPARATOR = 'SET_TEMPLATE_DATA_SOURCE_FILTER_COMPARATOR';
export const SET_TEMPLATE_DATA_SOURCE_FILTER_RIGHT_VALUE = 'SET_TEMPLATE_DATA_SOURCE_FILTER_RIGHT_VALUE';
export const SET_TEMPLATE_AGGREGATE_FUNCTION = 'SET_TEMPLATE_AGGREGATE_FUNCTION';

export const CALCULATE_TEMPLATE = 'CALCULATE_TEMPLATE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';